Docs: rename Enterprise to self-hosted
packagist/private-packagist-docs pull request #52
Opened 2021-10-29 09:53 UTC by wissem

2021-11-02 11:32 UTC, glaubinix requested changes
All the screenshots still have packagist-enterprise.com.lo as URL (not sure if we want to change) but the once showing Private Packagist also say Enterprise in the top navigation bar

2021-11-02 11:32 UTC, glaubinix commented on docs/self-hosted/installation.md
> +In the management console you will have to configure a few options before you can start the Private Packagist Self Hosted application.
```suggestion
In the management console you will have to configure a few options before you can start the Private Packagist Self-Hosted application.
```

2021-11-02 11:32 UTC, glaubinix commented on docs/self-hosted/installation.md
> +Save and apply the settings to start Private Packagist Self Hosted. Leave the Setup mode enabled.
```suggestion
Save and apply the settings to start Private Packagist Self-Hosted. Leave the Setup mode enabled.
```

2021-11-02 11:32 UTC, glaubinix commented on docs/self-hosted/installation.md
> +Once the application has started, click on the open link to access the Private Packagist Self Hosted Web Interface.
```suggestion
Once the application has started, click on the open link to access the Private Packagist Self-Hosted Web Interface.
```

2021-11-02 11:32 UTC, glaubinix commented on docs/self-hosted/installation.md
> +Within Private Packagist Self Hosted you now need to set up at least one user authentication method. You have the choice between authentication with email addresses and passwords and several OAuth in
```suggestion
Within Private Packagist Self-Hosted you now need to set up at least one user authentication method. You have the choice between authentication with email addresses and passwords and several OAuth integrations with third party services.
```

2021-11-02 11:32 UTC, glaubinix commented on features/integration-github-bitbucket-gitlab.md
> +* OAuth: Users authenticate on Private Packagist with their GitLab accounts. Please contact us to set this up for the cloud plan or follow [this setup](../docs/self-hosted/gitlab-integration-setup.md
```suggestion
* OAuth: Users authenticate on Private Packagist with their GitLab accounts. Please contact us to set this up for the cloud plan or follow [this setup](../docs/self-hosted/gitlab-integration-setup.md) for Self-Hosted.
```

2021-11-02 13:06 UTC, glaubinix commented on features/integration-github-bitbucket-gitlab.md
> +* OAuth: Users authenticate on Private Packagist with their GitHub accounts. Please contact us to set this up for the cloud plan or follow [this setup](../docs/self-hosted/github-integration-setup.md
```suggestion
* OAuth: Users authenticate on Private Packagist with their GitHub accounts. Please contact us to set this up for the cloud plan or follow [this setup](../docs/self-hosted/github-integration-setup.md) for Self-Hosted.
```

2021-11-02 13:06 UTC, glaubinix commented on features/integration-github-bitbucket-gitlab.md
> +* OAuth: Users authenticate on Private Packagist with their Bitbucket Server accounts. Please contact us to set this up for the cloud plan or follow [this setup](../docs/self-hosted/bitbucket-server-
```suggestion
* OAuth: Users authenticate on Private Packagist with their Bitbucket Server accounts. Please contact us to set this up for the cloud plan or follow [this setup](../docs/self-hosted/bitbucket-server-integration-setup.md) for Self-Hosted.
```

2021-11-05 11:51 UTC, glaubinix commented
There are some screenshots that are still referring the old URL
<img width="1496" alt="Screenshot 2021-11-05 at 11 44 49" src="https://user-images.githubusercontent.com/442056/140505812-7c27c5ef-e22c-4383-ae99-68de7fc810b9.png">
<img width="902" alt="Screenshot 2021-11-05 at 11 45 43" src="https://user-images.githubusercontent.com/442056/140505829-821e91af-19f8-4b67-8eb0-cdb61e5ed0a0.png">
<img width="1033" alt="Screenshot 2021-11-05 at 11 45 53" src="https://user-images.githubusercontent.com/442056/140505839-2c7441ae-5562-489d-9a17-e191ed03c20a.png">

Did you do something to pictures 2-6 on the installation guide? If you look at the browser bar, somehow it feels like those pictures are very squished together? Like the nav bar is using a different resolution to the rest of the picture
<img width="1072" alt="Screenshot 2021-11-05 at 11 49 04" src="https://user-images.githubusercontent.com/442056/140506243-e3b1dacb-426d-413f-82c6-9e12e565aba1.png">

2021-11-11 14:04 UTC, wissem commented
@glaubinix updated for all images including the squished ones

2021-11-11 14:36 UTC, glaubinix reviewed
Resources/public/img/docs/self-hosted/01-ssl-warning.png shows the wrong URL. Should be the one with the port 8800 see https://packagist.com/docs/enterprise/installation#replicated-setup

2021-11-11 15:23 UTC, glaubinix approved these changes

2021-11-11 15:23 UTC, merged