Self hosted Kubernetes Documentation
packagist/private-packagist-docs pull request #67
Opened 2022-12-08 15:13 UTC by glaubinix

2022-12-13 09:05 UTC, pscheit requested changes

2022-12-13 09:05 UTC, pscheit commented on docs/self-hosted/kubernetes.md
> +  * hub.docker.com/
```suggestion
  * hub.docker.com
```

2022-12-13 09:05 UTC, pscheit commented on docs/self-hosted/kubernetes.md
> +To learn more about options for the easy install script, please refer to the Replicated manual on Installing Replicated at https://help.replicated.com/docs/kubernetes/customer-installations/installin
```suggestion
To learn more about options for the easy install script, please refer to the Replicated manual on Installing Replicated at [https://help.replicated.com/docs/kubernetes/customer-installations/installing/](https://help.replicated.com/docs/kubernetes/customer-installations/installing/).
```

2022-12-13 09:05 UTC, pscheit commented on docs/self-hosted/kubernetes.md
> +  * hub.docker.com/
```suggestion
  * hub.docker.com
```

2022-12-13 17:00 UTC, zanbaldwin commented
- Would probably not make port 8800 a requirement - mention that in order to access the admin panel remotely then it would need to be forwarded to a port of their choosing (might be nice in the future to have a handy `kubectl apply` YAML file to provide instead of having to set up Nginx configuration).
- If the storage class used is Longhorn, at this point in time it does not support Kubernetes v..25+
- The Kots admin panel is available on install, but stops after a Ctrl-C. Is there a way for it to run continuously in the background like it does on regular Replicated?

2022-12-13 17:03 UTC, glaubinix commented
Thanks, will update the port thing. It's still required for embedded cluster. The storage class is up to them, so nothing we have to document. Unsure about the admin panel. Will look into this but I think the idea might be to just start it while you need it and shut it down when not because you don't want to expose services if you don't need them.

2023-02-21 15:47 UTC, pscheit approved these changes
historic day =)

2023-02-22 16:25 UTC, merged