clarify the context of the integration gitlab setup guide
packagist/private-packagist-docs pull request #73
Opened 2023-07-13 15:47 UTC by pscheit

![image](https://github.com/packagist/private-packagist-docs/assets/488189/ecfe5b18-5d5f-4998-aa52-8d1d8630d870)

2023-07-13 15:49 UTC, pscheit commented
If we would want to add that clarifying paragraph on top for gitlab, I would add one for github + bitbucket as well.

added the small other wished from @naderman , too

2023-07-13 16:19 UTC, glaubinix commented
Looks good. Feel free to add the paragraph to the other integrations too.

2023-07-14 06:35 UTC, pscheit commented
we used callout warning here
![image](https://github.com/packagist/private-packagist-docs/assets/488189/c16c6f47-3be8-4f0a-855b-d65e387c286a)

shall we
a) use callout warning everywhere
b) leave it there and have just a paragraph everywhere else
c) convert this warning to a paragraph to have it consistent?

2023-07-14 10:03 UTC, glaubinix commented
I would leave this as is. Bitbucket is a really different to GitHub and GitLab. They have different solutions for self-hosted vs cloud and the callout up there is the most important thing on that docs page. In 99% of all cases, you are trying to connect to a self-hosted instance of Bitbucket and not bitbucket.org.

2023-07-14 10:04 UTC, glaubinix approved these changes

2023-08-01 15:37 UTC, naderman requested changes

2023-08-01 15:37 UTC, naderman commented on docs/self-hosted/bitbucket-integration-setup.md
> +To setup a Bitbucket Integration with Private Packagist start by selecting "Bitbucket" as the platform and enter <i>https://bitbucket.org</i> as the base URL, as seen in the example below.
```suggestion
To setup a Bitbucket integration with Private Packagist start by selecting "Bitbucket" as the platform and enter <i>https://bitbucket.org</i> as the base URL, as seen in the example below.
```

was already wrong before, but worth fixing ;-)

2023-08-01 15:37 UTC, naderman commented on docs/self-hosted/bitbucket-integration-setup.md
> +Hit the “Add integration“ button on the admin page to get to the form below.
```suggestion
Hit the “Add Integration“ button on the admin page to get to the form below.
```

2023-08-01 15:37 UTC, naderman commented on docs/self-hosted/bitbucket-server-integration-setup.md
> +Hit the “Add integration“ button on the admin page to get to the form below.
```suggestion
Hit the “Add Integration“ button on the admin page to get to the form below. 
```

2023-08-01 15:37 UTC, naderman commented on docs/self-hosted/github-integration-setup.md
> +Hit the “Add integration“ button on the admin page to get to the form below.
```suggestion
Hit the “Add Integration“ button on the admin page to get to the form below.
```

2023-08-01 15:37 UTC, naderman commented on docs/self-hosted/gitlab-integration-setup.md
> +Hit the "Add integration" button on the admin page in Private Packagist Self-Hosted to get to the form below.
```suggestion
Hit the "Add Integration" button on the admin page in Private Packagist Self-Hosted to get to the form below. 
```

2023-08-02 09:56 UTC, merged