Composer: new docs page explaining the different authentication tokens
packagist/private-packagist-docs pull request #77
Opened 2023-10-03 16:23 UTC by glaubinix

2023-10-19 09:18 UTC, zanbaldwin approved these changes

2023-10-31 15:15 UTC, naderman requested changes

2023-10-31 15:17 UTC, glaubinix commented on docs/composer-authentication.md
> +### Private Packagist for Vendors customer tokens
ah yes, I see how this can be confusing

2023-10-31 15:19 UTC, glaubinix commented
Thank you!

2023-10-31 15:20 UTC, glaubinix commented on docs/composer-authentication.md
> +and asserting that the checksum is exactly eight characters long.
@naderman the part `using the prefix and random part convert the number to hexadecimal` reads a bit weird. Is this really correct?

2023-10-31 15:21 UTC, glaubinix commented on docs/composer-authentication.md
> +and asserting that the checksum is exactly eight characters long.
Did you mean `random part. Convert the number` to split this into two sentences?

2023-10-31 15:46 UTC, naderman commented on docs/composer-authentication.md
> +and asserting that the checksum is exactly eight characters long.
```suggestion
To calculate the checksum of a token, calculate the CRC32 checksum using the prefix and random part, and convert the number to hexadecimal while padding it to exactly 8 characters.
```

2023-10-31 15:49 UTC, glaubinix commented on docs/composer-authentication.md
> +and asserting that the checksum is exactly eight characters long.
ok, fixed

2023-10-31 16:02 UTC, naderman approved these changes

2023-10-31 16:02 UTC, merged