Bitbucket Server: add OAuth2 docs
packagist/private-packagist-docs pull request #84
Opened 2024-01-31 15:19 UTC by glaubinix

2024-02-01 11:19 UTC, pscheit requested changes

2024-02-01 11:31 UTC, pscheit commented on docs/self-hosted/bitbucket-server-oauth1-integration-setup.md
> +This is where we will need the "Client ID" and the "Public Key" that were previously generated on the Private Packagist integration form. Make sure the entire content of the "Public Key" field gets c
(stumbled over this in the past, too, i know this is the old docs)

2024-02-02 10:50 UTC, glaubinix commented on docs/self-hosted/bitbucket-server-integration-setup.md
> +![Bitbucket Configure Application Link](/Resources/public/img/docs/integration-setup/bitbucket-server-03-bitbucket-configure-application-link.png)
added

2024-02-02 10:54 UTC, glaubinix commented on docs/self-hosted/bitbucket-server-oauth1-integration-setup.md
> +This is where we will need the "Client ID" and the "Public Key" that were previously generated on the Private Packagist integration form. Make sure the entire content of the "Public Key" field gets c
Added a note

2024-02-05 12:20 UTC, merged